/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    MonadFrontline: {
      // ⚠️ TODO: Muhammet'in `yarn deploy --network monad_testnet` sonrası gelen adresle güncelle
      address: "0x0000000000000000000000000000000000000000",
      abi: [
        {
          type: "function",
          name: "claimTile",
          inputs: [
            { name: "tileId", type: "uint256", internalType: "uint256" },
            { name: "teamId", type: "uint8", internalType: "uint8" },
            { name: "multiplier", type: "uint8", internalType: "uint8" },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getBoard",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8[225]",
              internalType: "uint8[225]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "grid",
          inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "scores",
          inputs: [{ name: "", type: "uint8", internalType: "uint8" }],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "TileClaimed",
          inputs: [
            { name: "tileId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "teamId", type: "uint8", indexed: false, internalType: "uint8" },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
